color0       #090404
color8       #665353
color1       #A3A09D
color9       #A3A09D
color2       #B2B0AD
color10      #B2B0AD
color3       #C3C0BC
color11      #C3C0BC
color4       #D5D0CC
color12      #D5D0CC
color5       #E3DCD7
color13      #E3DCD7
color6       #E1E0DF
color14      #E1E0DF
color7       #c1c0c0
color15      #c1c0c0
