# Font Customizations
font_family Cousine Nerd Font

# Font Size
font_size 13

# Window padding
window_padding_width 8

# Background opacity
background_opacity 0.8

# Added by Gogh
include colors.conf

# Remove kitty closing confirmation
confirm_os_window_close 0

enable_audio_bell no
