themes:
  - name: "Zark"
    colors:
      - "#000000"
      - "#060606"
      - "#121212"
      - "#252525"
      - "#888888"
      - "#464646"
      - "#ABABAB"
      - "#696969"
      - "#D2D2D2"
      - "#ffffff"

  - name: "zarker"
    colors:
      - "#000000"
      - "#060606"
      - "#121212"
      - "#ABABAB"
      - "#D2D2D2"
      - "#ffffff"
