# Animations
animations {
    enabled = yes

    bezier = myBezier, 0.05, 0.9, 0.1, 1.0
    bezier = popOut,   0.05, 0.9, 0.1, 1.0

    animation = windows,        1, 7,   myBezier
    animation = windowsIn,      1, 7,   popOut, popin 10%
    animation = windowsOut,     1, 7,   myBezier, slide
    animation = border,         1, 10,  default
    animation = borderangle,    1, 8,   default
    animation = fade,           1, 7,   default
    animation = workspaces,     1, 7,   myBezier, slidevert
}
