# To fix some dragging with Xwayland.
windowrule = match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0, no_focus on

# Makes the waybar layer blur
layerrule = match:namespace waybar, blur on
layerrule = match:namespace waybar, ignore_alpha 0.2

# Makes the swaync notification layer blur
layerrule = match:namespace swaync-notification-window, blur on
layerrule = match:namespace swaync-notification-window, ignore_alpha 0.0

# Makes the swaync notification layer blur
layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace swaync-control-center, ignore_alpha 0.0

# Makes the rofi layer blur
layerrule = match:namespace rofi, blur on
layerrule = match:namespace rofi, ignore_alpha 0.0

# Ignore maximize requests from apps. 
windowrulev = suppressevent maximize, class:.*

# TerTime rules (first for float, second for size, third for position.)
windowrule = match:class tertime, float on
windowrule = match:class tertime, size 400 180
windowrule = match:class tertime, move 9 42

# Makes Calendar smaller and float by default.
windowrule = match:class org.gnome.Calendar, float on
windowrule = match:class org.gnome.Calendar, size 360 600
windowrule = match:class org.gnome.Calendar, move 781 258

# To open Audio Relay only on its dedicated workspace.
windowrule = match:class com-azefsw-audioconnect-desktop-app-MainKt, workspace 10
