[preferred]

# Uses hyprland's xdg portal as the default one
default=hyprland

# Uses GTK XDG portal for these certain things since hyprland don't do them anyways
# Why is it better than the fallback system? Becuase it doesn't have to fail first to then fallback on the GTK but rather calls GTK directly.
org.freedesktop.impl.portal.FileChooser=gtk
org.freedesktop.impl.portal.Settings=gtk
org.freedesktop.impl.portal.AppChooser=gtk
